### numpy的属性
 *  ndim：维度
 *  shape：行数和列数
 *  size：元素个数

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 3)
9


### numpy的创建：
* arange 创建数组
* linspace 创建指定数量等间隔的序列，实际生成一个等差数列
* logspace 用于生成等比数列
* ones、zeros、eye、empty 创建指定数据的数组，注意：empty创建的数组是有值的，数据接近0
* fromstring frombuffer 将字符串转化成ndarray对象
* fromfunction 矩阵的行号列号生成矩阵的元素


In [7]:
#linespace()
##################################################################################
a1 = np.linspace(0,10,7) # 生成首位是0，末位是10，含7个数的等差数列
print(a1)
print('##################################################################################')

#logspace()
##################################################################################
a2 = np.logspace(0,2,5)#生成首位是0，末位是100，含5个数的等比数列，0与2是10的指数
print(a2)
print('##################################################################################')

#frombuffer()
#################################################################################
a3 = "abcdef"
b = np.frombuffer(a,dtype=np.int8) # 因为一个字符为8为，所以指定dtype为np.int8
print(b) # 返回 [ 97  98  99 100 101 102]
print('#################################################################################')

#fromfunction()
#################################################################################
def func(i,j): 
    return i+j

a4 = np.fromfunction(func,(5,6)) 
# 第一个参数为指定函数，第二个参数为列表list或元组tuple,说明矩阵的大小
print(a4)
# 返回

#注意这里行号的列号都是从0开始的
####################################################################################

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
##################################################################################
[  1.           3.16227766  10.          31.6227766  100.        ]
##################################################################################
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 -16  63   0   0
   0   0   0   0   0  64   0   0   0   0   0   0   8  64   0   0   0   0
   0   0  16  64   0   0   0   0   0   0  20  64   0   0   0   0   0   0
 -16  63   0   0   0   0   0   0   0  64   0   0   0   0   0   0   8  64
   0   0   0   0   0   0  16  64   0   0   0   0   0   0  20  64   0   0
   0   0   0   0  24  64   0   0   0   0   0   0   0  64   0   0   0   0
   0   0   8  64   0   0   0   0   0   0  16  64   0   0   0   0   0   0
  20  64   0   0   0   0   0   0  24  64   0   0   0   0   0   0  28  64
   0   0   0   0   0   0   8  64   0   0   0   0   0   0  16  64   0   0
   0   0   0   0  20  6

### numpy的基本计算 
* numpy中的ndarray对象重载了许多运算符，使用这些运算符可以完成矩阵间对应元素的运算。


  * \+	矩阵对应元素相加
  * \-	矩阵对应元素相减
  * \*	矩阵对应元素相乘
  * /	矩阵对应元素相除，如果都是整数则取商
  * %	矩阵对应元素相除后取余数
  * \*\*	矩阵每个元素都取n次方，如**2：每个元素都取平方

### numpy的基本运算函数
  * np.sin(a)	对矩阵a中每个元素取正弦,sin(x)
  * np.cos(a)	对矩阵a中每个元素取余弦,cos(x)
  * np.tan(a)	对矩阵a中每个元素取正切,tan(x)
  * np.arcsin(a)	对矩阵a中每个元素取反正弦,arcsin(x)
  * np.arccos(a)	对矩阵a中每个元素取反余弦,arccos(x)
  * np.arctan(a)	对矩阵a中每个元素取反正切,arctan(x)
  * np.exp(a)	对矩阵a中每个元素取指数函数,ex
  * np.sqrt(a)	对矩阵a中每个元素开根号√x

### numpy的信息获取函数
 * 最大最小值 max(),min()
 * 平均值 mean()
 * 方差 var() 相当于函数mean(abs(x - x.mean())**2),其中x为矩阵
 * 标准差 std() 相当于sqrt(mean(abs(x - x.mean())**2))，或相当于sqrt(x.var())
 * 中值 median() 
 
 ### 最大值

In [8]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.max()) #获取整个矩阵的最大值 结果： 6
print(a.min()) #结果：1

# 可以指定关键字参数axis来获得行最大（小）值或列最大（小）值
# axis=0 行方向最大（小）值，即获得每列的最大（小）值
# axis=1 列方向最大（小）值，即获得每行的最大（小）值
# 例如

print(a.max(axis=0))
# 结果为 [4 5 6]

print(a.max(axis=1))
# 结果为 [3 6]

# 要想获得最大最小值元素所在的位置，可以通过argmax函数来获得
print(a.argmax(axis=1))
# 结果为 [2 2]

6
1
[4 5 6]
[3 6]
[2 2]


### 中值

In [9]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])

print(np.median(x))  # 对所有数取中值
# 结果
#3.5

print(np.median(x,axis=0))  # 沿第一维方向取中值
# 结果
#[ 2.5  3.5  4.5]

print(np.median(x,axis=1))  # 沿第二维方向取中值
# 结果
#[ 2.  5.]

3.5
[2.5 3.5 4.5]
[2. 5.]


### 求和

In [10]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print(a.sum())           # 对整个矩阵求和
# 结果 21

print(a.sum(axis=0)) # 对行方向求和
# 结果 [5 7 9]

print(a.sum(axis=1)) # 对列方向求和
# 结果 [ 6 15]

21
[5 7 9]
[ 6 15]


### 方差

In [11]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.var()) # 结果 2.91666666667

print(a.var(axis=0)) # 结果 [ 2.25  2.25  2.25]
print(a.var(axis=1)) # 结果 [ 0.66666667  0.66666667]

2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]


### 标准差

In [12]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.std()) # 结果 1.70782512766

print(a.std(axis=0)) # 结果 [ 1.5  1.5  1.5]
print(a.std(axis=1)) # 结果 [ 0.81649658  0.81649658]

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


### numpy的合并
* vstack() 上下合并
* hstack() 左右合并
* concatenate()多个数组的合并

In [14]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])       
print(np.vstack((A,B)))    # vertical stack
C = np.vstack((A,B))      
print(A.shape,C.shape)
print('\n\n')

D = np.hstack((A,B))       # horizontal stack
print(D)
# [1,1,1,2,2,2]
print(A.shape,D.shape)
# (3,) (6,)
print('\n\n')

C1 = np.concatenate((A,B,B,A),axis=0)
print(C1)
print('\n\n')

D1 = np.concatenate((A,B,B,A),axis=1)
print(D1)
print('\n\n')

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)



[1 1 1 2 2 2]
(3,) (6,)



[1 1 1 2 2 2 2 2 2 1 1 1]





AxisError: axis 1 is out of bounds for array of dimension 1

### numpy的分割
* split() 均等分割
* array_split() 可不均等分割